/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   my-element.js
 */

/**
 * `my-element`
 */
declare class MyElement extends PolymerElement {
  prop1: string|null|undefined;
}

declare global {

  interface HTMLElementTagNameMap {
    "my-element": MyElement;
  }
}

export {};
